package glureau.kdp.factorymethod.java;

/**
 * 
 * Common interface for products generated by the factory method. Modify it 
 * in order to add your products' expected features!
 * 
 */
public interface AbstractProduct {
	
	void feature();

}
